version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  redis-commander:
    image: dimdm/redis-commander
    container_name: redis-commander
    ports:
      - 8081:8081
    links:
      - redis

  nodebb:
    image: dimdm/nodebb:alpine
    container_name: nodebb
    environment:
      - "NODE_ENV=production"
    command: ./docker-start.sh
    volumes:
      - ./docker-start.sh:/opt/nodebb/docker-start.sh:ro
      - ./config.json:/opt/nodebb/config.json:rw
    links:
      - redis
    ports:
      - 4567:4567
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  weave:
    image: weaveworks/scope
    container_name: weave
    privileged: true
    pid: host
    labels:
      - works.weave.role=system
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - "CHECKPOINT_DISABLE=true"
    command: --probe.docker true
    ports:
      - 4040:4040
